# Generated by Django 6.1 on 2026-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name_en", models.CharField(max_length=150)),
                ("full_name_fa", models.CharField(max_length=150)),
                ("headline_en", models.CharField(max_length=200)),
                ("headline_fa", models.CharField(max_length=200)),
                ("bio_en", models.TextField()),
                ("bio_fa", models.TextField()),
                ("available_for_hire", models.BooleanField(default=True)),
                ("github_url", models.URLField()),
                ("linkedin_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton_key", 1)),
                        name="portfolio_profile_singleton_key_is_one",
                    )
                ],
            },
        ),
    ]
