# Generated by Django 6.1 on 2026-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_skillcategory_technology_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_fa", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description_en", models.TextField()),
                ("description_fa", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("demo_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="portfolio.technology"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-id"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "order"], name="project_pub_order_idx"
                    )
                ],
            },
        ),
    ]
