# Generated by Django 6.1 on 2026-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentlyBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_fa", models.CharField(max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Progress from 0 to 100"
                    ),
                ),
                ("current_phase_en", models.CharField(blank=True, max_length=100)),
                ("current_phase_fa", models.CharField(blank=True, max_length=100)),
                ("related_link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Currently Building",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree_en", models.CharField(max_length=150)),
                ("degree_fa", models.CharField(max_length=150)),
                ("institution_en", models.CharField(max_length=200)),
                ("institution_fa", models.CharField(max_length=200)),
                ("field_of_study_en", models.CharField(blank=True, max_length=150)),
                ("field_of_study_fa", models.CharField(blank=True, max_length=150)),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["-graduation_year", "order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_en", models.CharField(max_length=150)),
                ("position_fa", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=150)),
                ("company_url", models.URLField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-start_date", "order"],
            },
        ),
    ]
