# Generated by Django 6.1 on 2026-08-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_currentlybuilding_education_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("file", models.FileField(upload_to="resumes/")),
                ("version", models.CharField(blank=True, max_length=50)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Resumes",
                "ordering": ["-is_current", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="unique_current_resume",
                    )
                ],
            },
        ),
    ]
