# Generated by Django 6.1 on 2026-08-24 10:19

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                upload_to=apps.core.storage.SecureUploadTo("resumes/"),
                validators=[apps.core.validators.validate_resume_file],
                verbose_name="PDF File",
            ),
        ),
    ]
